version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: { interval: "daily" }
    open-pull-requests-limit: 10
    rebase-strategy: auto
    labels: [dependencies, github-actions]
